[workspace]
resolver = "3"
members = [
    "crates/terminal",
    "crates/alacrterm",
    "crates/terminal_view",
    "crates/util",
]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
terminal = { path = "crates/terminal" }
terminal_view = { path = "crates/terminal_view" }
util = { path = "crates/util" }

gpui = { package = "gpui", git = "https://github.com/gpui-ce/gpui-ce" }
gpui_platform = { git = "https://github.com/gpui-ce/gpui-ce" }
alacritty_terminal = "0.26"
anyhow = "1.0"
rust-embed = "8"
libc = "0.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
sysinfo = "0.39"
schemars = "1"
url = "2.2"
parking_lot = "0.12"
percent-encoding = "2.3"
futures = "0.3.32"
itertools = "0.15.0"
regex = "1.5"
dirs = "6.0"
globset = "0.4"
dunce = "1.0"
shlex = "2.0"
which = "8.0"
nix = { version = "0.31", features = ["user"] }
tendril = "0.4"
pretty_assertions = "1"

# [target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_System_Kernel",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }
