[package]
name = "alacrterm"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { workspace = true }
gpui-kit = { workspace = true }
anyhow.workspace = true
log.workspace = true
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
terminal = { workspace = true }
terminal_view = { workspace = true }
util = { workspace = true }